[asciidocExt]
workingFolderCurrent = true
extensions = ["asciidoctor-html5s"]
backend = "html5s"

[asciidocExt.attributes]
source-highlighter = "rouge"
toc = false

# [tableOfContents]
# startLevel = 1
# endLevel = 6
# ordered = false
