[asciidocExt]
workingFolderCurrent = true
#extensions = ["asciidoctor-html5s"]
backend = "html5"

[asciidocExt.attributes]
source-highlighter = "rouge"
toc = true

[tableOfContents]
startLevel = 1
endLevel = 6
ordered = false
