enableBlogPost = true
enableTOC = true
background = "images/vincentiu-solomon-ln5drpv_ImI-unsplash.jpg"
description = "Personal website and portfolio"

[newsletter]
enable = false

[darkMode]
provider = "darkreader"
enable = true
default = "system"

[logo]
main = "images/marko.png"
inverted = "images/marko.png"
favicon = "favicon-32x32.png"

[features.comment]
enable = true

[features.comment.giscus]
repo = "FunctionalHacker/korhonen.cc"
repoID = "R_kgDOHfIUew"
category = "Announcements"
categoryID = "DIC_kwDOHfIUe84CPnO-"
theme = "preferred_color_scheme"

[features.support]
enabled = true

[features.blog]
enable = true

[features.blog.sharebuttons]
facebook = true
twitter = true
linkedin = true
reddit = true
whatsapp = true
email = true
