background = "/images/vincentiu-solomon-ln5drpv_ImI-unsplash.jpg"
description = "Personal website, portfolio and blog of Marko Korhonen"

gitRepo = "https://git.korhonen.cc/FunctionalHacker/korhonen.cc"
gitBranch = "main"
gitForge = "gitea"

[newsletter]
enable = false

[logo]
main = "/images/marko.jpeg"
inverted = "/images/marko.jpeg"
favicon = "/favicon.png"

[features.toc]
enable = true

[features.flags]
enable = true
[[flags.flagOverwrites]]
languageCode = "en"
countryCode = "us"

[features.theme]
enable = true

[features.copyCodeButton]
enable = true

[features.comment]
enable = true
[features.comment.services.giscus]
repo = "FunctionalHacker/korhonen.cc"
repoID = "R_kgDOHfIUew"
category = "Announcements"
categoryID = "DIC_kwDOHfIUe84CPnO-"
theme = "preferred_color_scheme"

[features.support]
enable = true
[features.support.services.kofi]
user = "functionalhacker"
text = "Buy coffee"
textColor = "#f9fafc"
backgroundColor = "#f66400"

[features.blog]
enable = true
[features.blog.sharebuttons]
facebook = true
twitter = true
linkedin = true
reddit = true
whatsapp = true
email = true

[features.readingTime]
enable = true

[features.analytics]
enable = true
[features.analytics.services.umami]
scheme = "https"
instance = "umami.korhonen.cc"
id = "d79111e4-25ee-43d8-be20-5cd3a845a8cf"

[atom]
title="Korhonen.cc Blog"
subtitle="This blog explores open-source tools, self-hosted services, and the daily life of a developer."
uuid = "341a0375-31e6-47e9-a19f-f8e9a0436977"
mainSections = ["posts"]
[atom.dateFormat]
feed = "2006-01-02T15:04:05-07:00"
tag = "2006"
