background = "/images/vincentiu-solomon-ln5drpv_ImI-unsplash.jpg"
description = "Personal website and portfolio"

gitRepo = "https://git.korhonen.cc/FunctionalHacker/korhonen.cc"
gitBranch = "main"
gitForge = "gitea"

[newsletter]
enable = false

[logo]
main = "/images/marko.png"
inverted = "/images/marko.png"
favicon = "/favicon-32x32.png"

[features.toc]
enable = true

[features.darkMode]
enable = true

[features.comment]
enable = true
[features.comment.services.giscus]
repo = "FunctionalHacker/korhonen.cc"
repoID = "R_kgDOHfIUew"
category = "Announcements"
categoryID = "DIC_kwDOHfIUe84CPnO-"
theme = "preferred_color_scheme"

[features.support]
enabled = false

[features.blog]
enable = true
[features.blog.sharebuttons]
facebook = true
twitter = true
linkedin = true
reddit = true
whatsapp = true
email = true
