kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: klakegg/hugo:ext-asciidoctor-ci
  volumes:
  - name: output
    path: /korhonen.cc
  commands:
    - "hugo -d /korhonen.cc"

volumes:
- name: output
  host:
    path: /var/www/korhonen.cc
