kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:ext-asciidoctor-ci
  volumes:
  - name: output
    path: /korhonen.cc
  commands:
    - "ls /korhonen.cc"
    - "hugo -d /korhonen.cc"

volumes:
- name: output
  host:
    path: /var/www/korhonen.cc
