steps:
  build:
    image: git.korhonen.cc/functionalhacker/hugo-asciidoc-docker-ci:latest
    commands:
      - npm install
      - hugo --gc --cleanDestinationDir --enableGitInfo -d /korhonen.cc
    volumes:
      - /var/www/korhonen.cc:/korhonen.cc
    environment:
      - GOROOT=/usr/local/lib/go
