baseURL = 'https://korhonen.cc'
languageCode = 'en-us'
title = 'Marko Korhonen'
theme = 'toha'

enableEmoji = true

[languages]

[languages.en]
languageName = "English"
weight = 1

[languages.fi]
languageName = "Suomi"
weight = 2

[markup]

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[params]
enableBlogPost = false
enableTOC = false
background = "images/vincentiu-solomon-ln5drpv_ImI-unsplash.jpg"

[params.newsletter]
enable = false


[security]
enableInlineShortcodes = false

[security.exec]
allow = ['^asciidoctor$', '^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[security.funcs]
getenv = ['^HUGO_']

[security.http]
methods = ['(?i)GET|POST']

urls = ['.*']
