name: Build and deploy site

on: [push, workflow_dispatch]

jobs:
    deploy_site:
        name: Build and deploy site
        runs-on: docker
        container:
            image: ghcr.io/gohugoio/hugo
            options: --user root
            volumes:
                - caddy_korhonen_cc:/public

        steps:
            - name: Checkout
              uses: https://github.com/actions/checkout@v6

            - name: Install extra packages
              run: apk add asciidoctor tzdata ruby-rouge

            - name: Install NPM packages
              run: npm install

            - name: Run Hugo
              run: hugo --gc --minify --cleanDestinationDir -d /public
