name: Build and deploy site

on: [push]

env:
  GOROOT: /usr/local/lib/go

jobs:
  deploy_site:
    name: Build and deploy site
    runs-on: docker
    container:
      image: docker://hugomods/hugo:ci
      volumes:
        - caddy_korhonen_cc:/public

    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Install NPM packages
        run: npm install

      - name: Run Hugo
        run: hugo --gc --minify --cleanDestinationDir -d /public
