name: Build and deploy site

on: [push, workflow_dispatch]

env:
  GOROOT: /usr/local/lib/go

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    container:
      image: docker://hugomods/hugo:ci
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add extra dependencies
        run: apk add ruby-rouge

      - name: Install NPM packages
        run: npm install

      - name: Run Hugo
        run: hugo --gc --minify -d /public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /public

  deploy:
    name: Deploy site to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
